apiVersion: v1
kind: Service
metadata:
  name: blog-crud
spec:
  selector:
    app: blog-crud
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-crud
  template:
    metadata:
      labels:
        app: blog-crud
    spec:
      containers:
        - name: app
          image: daudayal1987/blog-crud:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DB
              value: blogdb
            - name: DB_AUTH
              value: ''
            - name: DB_USER
              value: ''
            - name: DB_PASS
              value: ''
            - name: DB_SERVERS
              value: mongo-db:27017
          imagePullPolicy: Always